'use client';

import Link from 'next/link';
import React, { useEffect, type ReactNode } from 'react';
import { type IconType } from 'react-icons';
import {
   RiCake2Fill as Cake,
   RiBriefcaseLine as Suitcase,
} from 'react-icons/ri';
// import { SlGraduation as Graduation } from 'react-icons/sl';
import { useLocomotiveScroll } from 'react-locomotive-scroll';

type Event = {
   title: string;
   details: string;
   date: string;
   icon: IconType;
   bg: string;
};
interface IHistory {
   year: string;
   events: Event[];
}

const HISTORY: IHistory[] = [
   {
      year: '2023',
      events: [
         {
            title: 'Looking for a remote / freelance opportunity.',
            details:
               'Seeking a new opportunity to further grow as a developer!',
            date: 'TBD',
            icon: Suitcase,
            bg: '#e3e3e3',
         },
      ],
   },
   {
      year: '2022',
      events: [
         {
            title: "I'm a Software Developer!",
            details:
               'Transitioned to the role as a software developer, taking leadership of a full-stack application that serves as presentation layer for data generated by one of our services',
            date: 'Jan 1, 2022',
            icon: Suitcase,
            bg: '#e3e3e3',
         },
      ],
   },
   {
      year: '2021',
      events: [
         {
            title: 'Intership as a React JS Software Developer',
            details: '',
            date: 'Nov 1, 2021',
            icon: Suitcase,
            bg: '#e3e3e3',
         },
      ],
   },
   {
      year: '1998',
      events: [
         {
            title: 'Day of Birth',
            details: 'Born in Karachi on the 1st of January 1998!',
            date: 'Jan 1, 1998',
            icon: Cake,
            bg: '#ffebeb',
         },
      ],
   },
];

const About = () => (
   <section data-scroll-id="about">
      <div className="container mx-auto pt-[1.5rem] pb-[2.5rem] font-normal text-white text-[clamp(.9375rem,_2.4vw,_1.09375rem)] md:text-[clamp(1rem,_1.5vw,_1.075rem)] md:leading-[1.45rem]">
         <div
            id="sticky"
            className="relative md:flex md:justify-between md:gap-[4em] md:items-start"
         >
            <AboutMeList>
               <div className="w-full">
                  <h3 className="mt-[1em] mb-[.5em] text-[1.75em] md:text-[clamp(1.75rem,_2.5vw,_2rem)] font-medium tracking-tight md:mt-[2rem] md:mb-[.9rem] font-fancy">
                     About me
                  </h3>

                  <p className="font-hellix text-justify">
                     {/* I am a creative web developer crafting high quality
                     interactive experiences through visuals and motion while
                     keeping in mind performance and accessibility and designer
                     eye for details. I implement design into highly interactive
                     experiences by paying close attention to the details,
                     animation and performance. */}
                     I am an imaginative web developer who crafts high-quality
                     interactive experiences using visuals and motion while
                     taking performance, accessibility and a designer&apos;s eye
                     for details into consideration. I incorporate design into
                     highly interactive experiences by giving careful
                     consideration to the specifics, animation, and performance.
                  </p>
                  <p className="mt-3 font-hellix text-justify">
                     I enjoy designing and building out seamless and intuitive
                     user experiences. As a developer, I have always looked for
                     the best way to find the exact means of expression, create
                     immersive experiences at the junction of magic, humans and
                     the mediums that bond them. If I&apos;m not making
                     websites, I&apos;m probably spending time with my family,
                     watching cricket or movies.
                  </p>
                  <p className="mt-3 font-hellix text-justify">
                     I&apos;m available for freelance or contract work, remote
                     or on site. Currently based in Karachi but willing to
                     relocate. Feel free to{' '}
                     <Link
                        className="decoration-white underline"
                        href="/contact"
                     >
                        contact me!
                     </Link>
                  </p>
               </div>
            </AboutMeList>
            <Timeline />
         </div>
      </div>
   </section>
);

interface Props {
   children: ReactNode;
}
const AboutMeList = ({ children }: Props) => {
   const isMd = true;
   const { scroll } = useLocomotiveScroll();

   useEffect(() => {
      scroll?.update();
      // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [isMd]);
   return isMd ? (
      <div
         data-scroll
         data-scroll-sticky
         data-scroll-target="#sticky"
         className="sticky mb-[3em] md:basis-[35%] md:max-w-[32rem]"
      >
         {children}
      </div>
   ) : (
      <div className="sticky mb-[3em]">{children}</div>
   );
};

function YearCard({ year, events }: { year: string; events: Event[] }) {
   return (
      <div className="[&:not(:first-child)]:mt-[2em]">
         <div className="grid grid-cols-[auto,1fr] gap-x-[.85em] grid-flow-row">
            <div />
            <div className="flex items-center gap-[1em] mb-[1.25em]">
               <h3 className="text-[1.5em] font-bold font-headings">{year}</h3>
               <div className="grow h-[1px] bg-gray-100" />
            </div>
            {events.map((event) => {
               const Icon = event.icon;
               return (
                  <React.Fragment key={event.title}>
                     <div className="flex flex-col items-center">
                        <div
                           style={{ backgroundColor: event.bg }}
                           className="p-[.55em] rounded-full"
                        >
                           <Icon className="dark:text-slate-800" />
                        </div>
                        <div className="w-[1px] h-full bg-gray-300" />
                     </div>

                     {/* event details */}
                     <div className="flex flex-col mb-[1.5em]">
                        <b className="block text-[1.125em] font-title">
                           {event.title}
                        </b>
                        <span className="inline-block mt-[.1em] text-[.925em] text-gray-400 font-hellix">
                           {event.date}
                        </span>
                        <p className="mt-[.5em] tracking-wide text-[.95em] text-gray-200 font-ivy-mode">
                           {event.details}
                        </p>
                     </div>
                  </React.Fragment>
               );
            })}
         </div>
      </div>
   );
}
const Timeline = () => (
   <div className="md:basis-[70%]">
      <h4 className="mb-[.25em] text-[1.75em] text-right font-medium tracking-tight md:text-[clamp(1.75rem,_2.5vw,_2rem)] md:pt-[.6em] md:pb-[.2em] lg:pt-[1em] lg:pb-[.4em]">
         Timeline
      </h4>
      <div>
         {HISTORY.map((timeline) => (
            <YearCard {...timeline} key={timeline.year} />
         ))}
      </div>
   </div>
);

export default About;
